CREATE TABLE CINEMA(
	ID_CINEMA NUMBER NOT NULL,
	NOME VARCHAR2(200) NOT NULL,
	ESTADO VARCHAR2(200) NOT NULL,
	CIDADE VARCHAR2(200) NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	PRIMARY KEY(ID_CINEMA)
	
);

CREATE TABLE FILME(
	ID_FILME NUMBER NOT NULL,
	NOME VARCHAR2(200) NOT NULL,
	IDIOMA VARCHAR2(200) NOT NULL,
	CLASSIFICACAO NUMBER NOT NULL,
	DURACAO NUMBER NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	PRIMARY KEY(ID_FILME)
);

CREATE TABLE CLIENTE(
	ID_CLIENTE NUMBER NOT NULL,
	PRIMEIRO_NOME VARCHAR2(200) NOT NULL,
	ULTIMO_NOME VARCHAR2(200) NOT NULL,
	CPF VARCHAR2(11) UNIQUE NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE INGRESSO(
	ID_INGRESSO NUMBER NOT NULL,
	ID_FILME NUMBER NOT NULL,
	ID_CLIENTE NUMBER,
	ID_CINEMA NUMBER NOT NULL,
	VALOR NUMBER NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	DISPONIBILIDADE CHAR NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	CONSTRAINT FK_INGRESSO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
	CONSTRAINT FK_INGRESSO_FILME FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME) ,
	CONSTRAINT FK_INGRESSO_CINEMA FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(ID_CINEMA), 
	PRIMARY KEY(ID_INGRESSO)
);

CREATE SEQUENCE SEQ_ID_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_CINEMA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_FILME
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_INGRESSO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO FILME
VALUES (SEQ_ID_FILME.nextval, 'Halloween Ends', 'LEGENDADO', 18, 111, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'Morte, Morte, Morte', 'DUBLADO', 16, 95, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'As Aventuras de Tadeo e a Tábua de Esmeralda', 'LEGENDADO', 0, 9, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'Os Suburbanos - O FilmeEntity', 'DUBLADO', 14, 85, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'Órfã 2: A Origem', 'LEGENDADO', 16, 98, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'Minions 2: A Origem de Gru', 'DUBLADO', 0, 94, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'A Liga dos Superpets', 'LEGENDADO', 0, 106, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'IngressoEntity Para o Paraíso', 'DUBLADO', 12, 102, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'A Mulher Rei', 'LEGENDADO', 14, 134, 'S');
INSERT INTO FILME 
VALUES (SEQ_ID_FILME.nextval, 'Adão Negro', 'DUBLADO', 14, 125, 'S');

INSERT INTO CINEMA VALUES 
(SEQ_ID_CINEMA.nextval, 'GNC Iguatemi', 'RS', 'Porto Alegre', 'S');
INSERT INTO CINEMA VALUES 
(SEQ_ID_CINEMA.nextval, 'Cinemark Barra Sul', 'RS', 'Porto Alegre', 'S');
INSERT INTO CINEMA VALUES 
(SEQ_ID_CINEMA.nextval, 'Cinemark Wallig', 'RS', 'Porto Alegre', 'S');
INSERT INTO CINEMA 
VALUES (SEQ_ID_CINEMA.nextval, 'UCI ParkShopping Canoas', 'RS', 'Porto Alegre', 'S');
INSERT INTO CINEMA 
VALUES (SEQ_ID_CINEMA.nextval, 'Cinemark Canoas', 'RS', 'Porto Alegre', 'S');
INSERT INTO CINEMA 
VALUES (SEQ_ID_CINEMA.nextval, 'Centerplex Caruaru', 'PE', 'Caruaru', 'S');
INSERT INTO CINEMA 
VALUES (SEQ_ID_CINEMA.nextval, 'Cinepolis Patteo Olinda', 'PE', 'Olinda', 'S');

INSERT INTO CLIENTE 
VALUES (SEQ_ID_CLIENTE.nextval, 'Vinicius', 'Assunção', '31816219002', TO_DATE('22/06/1999','dd-mm-yyyy'), 'vinicius-assuncao90@nine9.com.br', 'S');
INSERT INTO CLIENTE 
VALUES (SEQ_ID_CLIENTE.nextval, 'Filipe', 'Nascimento', '82766295470', TO_DATE('05/06/1995','dd-mm-yyyy'), 'filipe.isaac.nascimento@djapan.com.br', 'S');
INSERT INTO CLIENTE 
VALUES (SEQ_ID_CLIENTE.nextval, 'Isabella',  'Vieira', '81863960988', TO_DATE('09/07/1976','dd-mm-yyyy'), 'isabella_vieira@dc4.com.br', 'S');
INSERT INTO CLIENTE 
VALUES (SEQ_ID_CLIENTE.nextval, 'Nina', 'Freitas', '98827209514', TO_DATE('16/03/1951','dd-mm-yyyy'), 'nina.fernanda.freitas@arosacampinas.com.br', 'S');
INSERT INTO CLIENTE 
VALUES (SEQ_ID_CLIENTE.nextval, 'Fátima', 'Rosa', '40407480692', TO_DATE('06/10/1996','dd-mm-yyyy'), 'fatima-darosa74@skyzepp.com', 'S');
INSERT INTO CLIENTE 
VALUES (SEQ_ID_CLIENTE.nextval, 'Nicolas', 'Silveira', '10601608119', TO_DATE('03/05/1992','dd-mm-yyyy'), 'nicolas-silveira87@vasconcelosdias.com', 'S');
INSERT INTO CLIENTE 
VALUES (SEQ_ID_CLIENTE.nextval, 'Nair', 'Sales', '52700584058', TO_DATE('03/05/1992','dd-mm-yyyy'), 'nairmalusales@bravo.com.br', 'S');

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'), 'S', 'S');

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 5, 5, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 5, 5, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 5, 5, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 5, 5, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBILIDADE, ATIVO) 
VALUES (SEQ_ID_INGRESSO.nextval, 6, 6, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S', 'S');


