CREATE TABLE CARGO (
    ID_CARGO NUMBER NOT NULL,
    NOME varchar2(512) UNIQUE NOT NULL,
    PRIMARY KEY(ID_CARGO)
);

CREATE TABLE USUARIO(
    ID_USUARIO NUMBER NOT NULL,
    EMAIL varchar2(512) UNIQUE NOT NULL,
    SENHA varchar2(512) NOT NULL,
    ATIVO CHAR DEFAULT 'S' NOT NULL ,
    PRIMARY KEY(ID_USUARIO)
    
);

CREATE TABLE USUARIO_CARGO (
    ID_USUARIO NUMBER NOT NULL,
    ID_CARGO NUMBER NOT NULL,
    PRIMARY KEY(ID_USUARIO, ID_CARGO),
    CONSTRAINT FK_USUARIO_CARGO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO),
  	CONSTRAINT FK_USUARIO_CARGO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE CINEMA(
	ID_CINEMA NUMBER NOT NULL,
	ID_USUARIO NUMBER NOT NULL,
	NOME VARCHAR2(200) NOT NULL,
	ESTADO VARCHAR2(200) NOT NULL,
	CIDADE VARCHAR2(200) NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	PRIMARY KEY(ID_CINEMA),
	CONSTRAINT FK_USUARIO_CINEMA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE FILME(
	ID_FILME NUMBER NOT NULL,
	NOME VARCHAR2(200) NOT NULL,
	IDIOMA VARCHAR2(200) NOT NULL,
	CLASSIFICACAO NUMBER NOT NULL,
	DURACAO NUMBER NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	PRIMARY KEY(ID_FILME)
);

CREATE TABLE CLIENTE(
	ID_CLIENTE NUMBER NOT NULL,
	ID_USUARIO NUMBER NOT NULL,
	PRIMEIRO_NOME VARCHAR2(200) NOT NULL,
	ULTIMO_NOME VARCHAR2(200) NOT NULL,
	CPF VARCHAR2(11) UNIQUE NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	PRIMARY KEY(ID_CLIENTE),
	CONSTRAINT FK_USUARIO_CLIENTE FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE INGRESSO(
	ID_INGRESSO NUMBER NOT NULL,
	ID_FILME NUMBER NOT NULL,
	ID_CLIENTE NUMBER,
	ID_CINEMA NUMBER NOT NULL,
	VALOR NUMBER NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	DISPONIBILIDADE CHAR DEFAULT 'S' NOT NULL,
	ATIVO CHAR DEFAULT 'S' NOT NULL ,
	CONSTRAINT FK_INGRESSO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
	CONSTRAINT FK_INGRESSO_FILME FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME) ,
	CONSTRAINT FK_INGRESSO_CINEMA FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(ID_CINEMA), 
	PRIMARY KEY(ID_INGRESSO)
);

CREATE SEQUENCE seq_usuario
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_cargo
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE SEQ_ID_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_CINEMA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_FILME
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_INGRESSO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_ADMIN'); -- 1

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_CLIENTE'); -- 2

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_CINEMA'); -- 3

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_RECCLIENTE'); -- 4

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_RECCINEMA'); -- 5

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_RECADMIN'); -- 6