INSERT INTO USUARIO (ID_USUARIO, EMAIL, SENHA)
VALUES (
    SEQ_USUARIO.nextval,
    'vinicius-assuncao90@nine9.com.br',
    '$e0801$4+EBgXSlICuhoIS+FtgDDcqgDRg93P/3Nf16EIV+0B43Xf2Zei9fW8bFNd+Di6Fs7ZXD2jY47lsBRJe+gAbyyw==$8bMLnYwBPBXj9ZFh4wNuSRn0zaveOL0irfvx0tm/dDA='
);

INSERT INTO USUARIO (ID_USUARIO, EMAIL, SENHA)
VALUES (
    SEQ_USUARIO.nextval,
    'filipe.isaac.nascimento@djapan.com.br',
    '$e0801$4+EBgXSlICuhoIS+FtgDDcqgDRg93P/3Nf16EIV+0B43Xf2Zei9fW8bFNd+Di6Fs7ZXD2jY47lsBRJe+gAbyyw==$8bMLnYwBPBXj9ZFh4wNuSRn0zaveOL0irfvx0tm/dDA='
);

INSERT INTO USUARIO (ID_USUARIO, EMAIL, SENHA)
VALUES (
    SEQ_USUARIO.nextval,
    'isabella_vieira@dc4.com.br',
    '$e0801$4+EBgXSlICuhoIS+FtgDDcqgDRg93P/3Nf16EIV+0B43Xf2Zei9fW8bFNd+Di6Fs7ZXD2jY47lsBRJe+gAbyyw==$8bMLnYwBPBXj9ZFh4wNuSRn0zaveOL0irfvx0tm/dDA='
);

INSERT INTO USUARIO (ID_USUARIO, EMAIL, SENHA)
VALUES (
    SEQ_USUARIO.nextval,
    'nina.fernanda.freitas@arosacampinas.com.br',
    '$e0801$4+EBgXSlICuhoIS+FtgDDcqgDRg93P/3Nf16EIV+0B43Xf2Zei9fW8bFNd+Di6Fs7ZXD2jY47lsBRJe+gAbyyw==$8bMLnYwBPBXj9ZFh4wNuSRn0zaveOL0irfvx0tm/dDA='
);

INSERT INTO USUARIO (ID_USUARIO, EMAIL, SENHA)
VALUES (
    SEQ_USUARIO.nextval,
    'fatima-darosa74@skyzepp.com',
    '$e0801$4+EBgXSlICuhoIS+FtgDDcqgDRg93P/3Nf16EIV+0B43Xf2Zei9fW8bFNd+Di6Fs7ZXD2jY47lsBRJe+gAbyyw==$8bMLnYwBPBXj9ZFh4wNuSRn0zaveOL0irfvx0tm/dDA='
);

INSERT INTO USUARIO (ID_USUARIO, EMAIL, SENHA)
VALUES (
    SEQ_USUARIO.nextval,
    'nicolas-silveira87@vasconcelosdias.com',
    '$e0801$4+EBgXSlICuhoIS+FtgDDcqgDRg93P/3Nf16EIV+0B43Xf2Zei9fW8bFNd+Di6Fs7ZXD2jY47lsBRJe+gAbyyw==$8bMLnYwBPBXj9ZFh4wNuSRn0zaveOL0irfvx0tm/dDA='
);

INSERT INTO USUARIO (ID_USUARIO, EMAIL, SENHA)
VALUES (
    SEQ_USUARIO.nextval,
    'nairmalusales@bravo.com.br',
    '$e0801$4+EBgXSlICuhoIS+FtgDDcqgDRg93P/3Nf16EIV+0B43Xf2Zei9fW8bFNd+Di6Fs7ZXD2jY47lsBRJe+gAbyyw==$8bMLnYwBPBXj9ZFh4wNuSRn0zaveOL0irfvx0tm/dDA='
);

INSERT INTO USUARIO_CARGO (ID_USUARIO, ID_CARGO)
VALUES (1, 2);

INSERT INTO USUARIO_CARGO (ID_USUARIO, ID_CARGO)
VALUES (2, 2);

INSERT INTO USUARIO_CARGO (ID_USUARIO, ID_CARGO)
VALUES (3, 2);

INSERT INTO USUARIO_CARGO (ID_USUARIO, ID_CARGO)
VALUES (4, 2);

INSERT INTO USUARIO_CARGO (ID_USUARIO, ID_CARGO)
VALUES (5, 2);

INSERT INTO USUARIO_CARGO (ID_USUARIO, ID_CARGO)
VALUES (6, 2);

INSERT INTO USUARIO_CARGO (ID_USUARIO, ID_CARGO)
VALUES (7, 2);

INSERT INTO CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, DATA_NASCIMENTO)
VALUES (SEQ_ID_CLIENTE.nextval, 1,  'Vinicius', 'Assunção', '31816219002', TO_DATE('22/06/1999','dd-mm-yyyy'));

INSERT INTO CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, DATA_NASCIMENTO)
VALUES (SEQ_ID_CLIENTE.nextval, 2, 'Filipe', 'Nascimento', '82766295470', TO_DATE('05/06/1995','dd-mm-yyyy'));

INSERT INTO CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, DATA_NASCIMENTO)
VALUES (SEQ_ID_CLIENTE.nextval, 3, 'Isabella',  'Vieira', '81863960988', TO_DATE('09/07/1976','dd-mm-yyyy'));

INSERT INTO CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, DATA_NASCIMENTO)
VALUES (SEQ_ID_CLIENTE.nextval, 4, 'Nina', 'Freitas', '98827209514', TO_DATE('16/03/1951','dd-mm-yyyy'));

INSERT INTO CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, DATA_NASCIMENTO)
VALUES (SEQ_ID_CLIENTE.nextval, 5, 'Fátima', 'Rosa', '40407480692', TO_DATE('06/10/1996','dd-mm-yyyy'));

INSERT INTO CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, DATA_NASCIMENTO)
VALUES (SEQ_ID_CLIENTE.nextval, 6, 'Nicolas', 'Silveira', '10601608119', TO_DATE('03/05/1992','dd-mm-yyyy'));

INSERT INTO CLIENTE (ID_CLIENTE, ID_USUARIO, PRIMEIRO_NOME, ULTIMO_NOME, CPF, DATA_NASCIMENTO)
VALUES (SEQ_ID_CLIENTE.nextval, 7, 'Nair', 'Sales', '52700584058', TO_DATE('03/05/1992','dd-mm-yyyy'));