INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'Halloween Ends', 'LEGENDADO', 18, 111);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'Morte, Morte, Morte', 'DUBLADO', 16, 95);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'As Aventuras de Tadeo e a Tábua de Esmeralda', 'LEGENDADO', 0, 90);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'Os Suburbanos - O FilmeEntity', 'DUBLADO', 14, 85);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'Órfã 2: A Origem', 'LEGENDADO', 16, 98);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'Minions 2: A Origem de Gru', 'DUBLADO', 0, 94);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'A Liga dos Superpets', 'LEGENDADO', 0, 106);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'IngressoEntity Para o Paraíso', 'DUBLADO', 12, 102);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'A Mulher Rei', 'LEGENDADO', 14, 134);
INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'Adão Negro', 'DUBLADO', 14, 125);

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 3, 2, 30, TO_DATE('05/11/2022 15:45','dd-mm-yyyy hh24:mi'));

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('06/11/2022 21:30','dd-mm-yyyy hh24:mi'));

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 4, 4, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 4, 4, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 4, 4, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 4, 4, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA)
VALUES (SEQ_ID_INGRESSO.nextval, 4, 4, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'));